### ISSUE TITLE
Compilation instructions/Dependencies list

### ISSUE THREAD

**Issue by hellocatfood** [fundamental/oscprompt#7]
I'm attempting compile oscprompt on Ubuntu 19.10. I figured that it likely required cmake but when trying to compile I got this error:

```
-- Checking for one of the modules 'liblo>=0.25'
CMake Error at /usr/share/cmake-3.13/Modules/FindPkgConfig.cmake:679 (message):
  None of the required 'liblo>=0.25' found
Call Stack (most recent call first):
  CMakeLists.txt:6 (pkg_search_module)


-- Checking for one of the modules 'jack'
CMake Error at CMakeLists.txt:20 (add_subdirectory):
  The source directory

	/home/hellocatfood/Desktop/oscprompt/rtosc

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/home/hellocatfood/Desktop/oscprompt/CMakeFiles/CMakeOutput.log".
```

Is there a complete list of dependencies and compilation instructions?

**Comment by JohannesLorenz** [comment]
@hellocatfood Does `git submodule update --init` help?

**Comment by hellocatfood** [comment]
`git submodule update --init` downloaded rtosc. I ran cmake again but it revealed other dependencies needed
```
-- PkgConfig enabled  -- package found
-- Liblo disabled     -- package NOT found
-- JACK disabled      -- package NOT found
-- NTK disabled       -- package NOT found
-- Perf Test(s) disabled
-- FLTK disabled      -- package NOT found
-- Configuring incomplete, errors occurred!
```

Installed these with `sudo apt-get install liblo-dev libjack-jackd2-dev libfltk1.3-dev` but I can't work out which package NTK is in.

**Comment by fundamental** [comment]
Once you have the rtosc submodule checked out you only need liblo, all
other listed dependencies are for API usage examples of the rtosc
sub-library, not oscprompt itself.

**Comment by hellocatfood** [comment]
Thanks for your help! All working now.

I've proposed an update to the README with these instruction #8
